### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by eretenal** [cndaqiang/AirTest_MobileAuto_WZRY#10]
运行之后显示这是为什么
![QQ截图20240603205137](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/111845288/0b6200c7-910e-4e9e-b7a6-8c12cc12b061)

**Comment by cndaqiang** [comment]
认真阅读: https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/blob/master/README.md
<img width="659" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/43e910bf-0d19-4f78-ba29-d296f5abdc10">

**Comment by eretenal** [comment]
大佬，是按照那种方法来的，但是运行就会报错，这是为什么？我点击运行，就会卡住

**Comment by eretenal** [comment]
能讲明白点么？没动

**Comment by cndaqiang** [comment]
> 能讲明白点么？没动
0. 我不知道你那边的任何信息：安卓设备是什么？怎么adb链接的？改了哪些代码？
-----------------
2. 现在只能看到，应该是脚本没有找到你的模拟器/手机，尝试重启模拟器，所以在启动HD-Player.exe(我电脑上安装的Bluestack的模拟器)，你电脑上没有，所有报错
----------------------
3. 但是我不知道你是否改了代码，你的截图中并没有显示连接失败等信息，而是直接启动HD-Player.exe。 我不清楚为什么会这样报错
-----------
4. 如果还是不行，就全部在终端运行吧：
windows安装个python，按照教程pip安装下依赖就行

**Comment by eretenal** [comment]
好的谢谢大佬，有视频教学么？

**Comment by cndaqiang** [comment]
> 好的谢谢大佬，有视频教学么？

🤦‍没有，我账号都刷完了，没有动力录视频了。

**Comment by cndaqiang** [comment]
使用最新版的程序：https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/releases/tag/1.1.6
@eretenal 增加了屏幕输出
