### ISSUE TITLE
搞不懂怎么搭建运行

### ISSUE THREAD

**Issue by 1181691792** [cndaqiang/AirTest_MobileAuto_WZRY#4]
1

**Comment by cndaqiang** [comment]
1. 下载最新代码后解压
https://codeload.github.com/cndaqiang/AirTest_MobileAuto_WZRY/zip/refs/heads/master

2. 如果是安卓手机，需要自己打开无线ADB后(该方法自己搜索引擎解决)。 模拟器直接打开设置中的ADB开关即可.  容器安卓、苹果手机等其他情况见https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/blob/master/howtorun.md

在object.py中填入自己的手机/模拟器的ip和端口，如果有多台设备则填写多个
<img width="421" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/d95712a8-a1d0-453c-9394-ae139610264b">

3. 电脑安装python
按照https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/blob/master/howtorun.md
安装python的依赖

4. 运行
单设备运行
```
python object.py
```
更多方式
https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/blob/master/howtorun.md

**Comment by cndaqiang** [comment]
@1181691792
