### ISSUE TITLE
使用指南

### ISSUE THREAD

**Issue by cndaqiang** [cndaqiang/AirTest_MobileAuto_WZRY#5]
## 不要直接点击object.py运行
* 要么在cmd/powershell/terminal中运行
* 要么使用airTestIDE运行

## 简易版
* [下载最最新代码](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY)
* 修改代码中客户端的ip地址`auto_airtest>LINK_dict[i]=`
* 配置[控制端、客户端](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/blob/master/howtorun.md)

## 备注
* 脚本是在分辨率`960*540`的模拟器下采样的图片, 2k屏的手机大部分功能可以使用,存在极个别图片无法识别的可能行, 若有问题，用AirTest IDE中的touch功能重新采样即可

## 下面是不同的案例

**Comment by cndaqiang** [comment]
## 全终端控制单台小米手机示例
### 电脑配置
- 安装python
- 安装python库、有些系统需要修改airtest代码,详细见(howtorun.md)[https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/blob/master/howtorun.md]

### 手机打开ADB无线配对,电脑adb连接
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/879d20d4-5d6a-4397-9809-b63cf2b488b7)

```
(base) cndaqiang@macmini ~$ adb pair 192.168.12.109:39833
Enter pairing code: 527695
Successfully paired to 192.168.12.109:39833 [guid=adb-4e86ac13-GhtB4l]
#注意配对端口和连接端口不一样
(base) cndaqiang@macmini ~$ adb connect 192.168.12.109:41857
connected to 192.168.12.109:41857
```

### 修改本仓库代码
```
(base) cndaqiang@macmini tmp$ wget https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/archive/refs/tags/1.0.3.zip
--2024-01-14 22:21:10--  https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/archive/refs/tags/1.0.3.zip
正在解析主机 github.com (github.com)... 20.205.243.166
正在连接 github.com (github.com)|20.205.243.166|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：https://codeload.github.com/cndaqiang/AirTest_MobileAuto_WZRY/zip/refs/tags/1.0.3 [跟随至新的 URL]
--2024-01-14 22:21:10--  https://codeload.github.com/cndaqiang/AirTest_MobileAuto_WZRY/zip/refs/tags/1.0.3
正在解析主机 codeload.github.com (codeload.github.com)... 20.205.243.165
正在连接 codeload.github.com (codeload.github.com)|20.205.243.165|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：未指定 [application/zip]
正在保存至: “1.0.3.zip”

1.0.3.zip                             [    <=>                                                       ]   2.93M  4.60MB/s  用时 0.6s

2024-01-14 22:21:12 (4.60 MB/s) - “1.0.3.zip” 已保存 [3077386]

(base) cndaqiang@macmini tmp$ unzip 1.0.3.zip
(base) cndaqiang@macmini tmp$ cd  AirTest_MobileAuto_WZRY-1.0.3/
```
 修改这一行,填入刚才连接的端口和ip
<img width="738" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/b687cb74-7b81-4acf-85fd-8885cb235af3">
启动(保持手机屏幕不锁定)
```
(base) cndaqiang@macmini AirTest_MobileAuto_WZRY-1.0.3$ ./object.py
[01-14 22:26:34](0/1)(0/1):LINK=Android:///192.168.12.109:41857
[01-14 22:26:34](0/1)(0/1):设备类型=android
[01-14 22:26:34](0/1)(0/1):mynode=0
[01-14 22:26:34](0/1)(0/1):totalnode=1
[01-14 22:26:34](0/1)(0/1):APPID=com.tencent.tmgp.sgame
[01-14 22:26:34](0)Android:///192.168.12.109:41857:开始第1/4次连接
[01-14 22:26:36](0)Android:///192.168.12.109:41857:链接成功
[01-14 22:26:36](0)对战模式:5v5匹配
[01-14 22:26:36](0)remove[(0)NeedRebarrier.txt]
[01-14 22:26:36](0)不存在[(0)NeedRebarrier.txt]
```

**Comment by cndaqiang** [comment]
## 图形化控制单台小米手机示例
### 电脑下载AieTest并安装打开
### 电脑无线连接手机的ADB(同上)
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/879d20d4-5d6a-4397-9809-b63cf2b488b7)

```
(base) cndaqiang@macmini ~$ adb pair 192.168.12.109:39833
Enter pairing code: 527695
Successfully paired to 192.168.12.109:39833 [guid=adb-4e86ac13-GhtB4l]
#注意配对端口和连接端口不一样
(base) cndaqiang@macmini ~$ adb connect 192.168.12.109:41857
connected to 192.168.12.109:41857
```
### 电脑AirTest打开下载的代码,做同样的修改
<img width="1080" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/01bf5294-71c0-4fbc-86aa-2c67988d7376">
保存后，点击运行
<img width="343" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/cb3ee43f-6e77-4056-ae9f-2acbfbe838a7">
这里显示日志
<img width="637" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/c8b05b8a-ff6f-4e98-9ca3-6de40a371564">

**Comment by cndaqiang** [comment]
## Windows全新安装python、依赖+雷电模拟器
### Windows安装python
`PowerShell`执行python,会弹出窗口点击安装
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/0524a570-c786-451d-b7b7-eb332a189a44)
安装完成后执行下面命令
```
python.exe -m pip install --upgrade pip
python -m pip  install -i https://pypi.tuna.tsinghua.edu.cn/simple  airtest
python -m pip  install -i https://pypi.tuna.tsinghua.edu.cn/simple pathos
```
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/676fd3d9-2b7d-44d3-862f-6898125a134a)

### 雷电模拟器配置
我之前一直使用的是Bluestack适合多开,这次尝试下雷电,使用的版本[雷电模拟器 9.0.65.0 去广告绿色版](https://www.osssr.com/4226.html),设置如下
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/4d6cf286-f337-48e2-857a-acc6eb6ad9ab)
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/98ead277-8c3f-4fab-ba8b-7fa7d0a665c6)

### 雷电模拟器自己安装WZRY,登录账户
初次使用,强烈建议WZRY的设置中采用低画质、低刷新率等, 最好自己点击一次5v5人机对战,因为在信设备上登录,对战过程会各种提示新赛季的新功能

### 下载代码执行
从这里[下载](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY)zip后
<img width="1075" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/c07fd912-9153-4ac0-8a4d-0b98117d61ee">
解压，进入到解压目录,直接运行. 
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/45e059d4-0d8c-45ed-8a3c-6d72eb8b36d2)
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/a0102793-6e9b-4275-b74a-ea0379b93e15)

**Comment by Galaxyduan** [comment]
脚本运行闪退 无法加载啊

**Comment by cndaqiang** [comment]
> 脚本运行闪退 无法加载啊

提供完整的运行截图 @Galaxyduan

**Comment by Pain2021** [comment]
![1707720128534](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/70928776/44b34aaf-7ecb-4318-a885-c06d34228607)这种怎么搞

**Comment by cndaqiang** [comment]
> ![1707720128534](https://private-user-images.githubusercontent.com/70928776/303982933-44b34aaf-7ecb-4318-a885-c06d34228607.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTQ5MjksIm5iZiI6MTcwNzgxNDYyOSwicGF0aCI6Ii83MDkyODc3Ni8zMDM5ODI5MzMtNDRiMzRhYWYtN2VjYi00MzE4LWE4ODUtYzA2ZDM0MjI4NjA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA4NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYzU5ODhmMWE1YTJmMmFkMzVmZmJkYjU3MjU3ZGQ4NzI2NmNhMzdkOTlmYzExZmI4MjNiNWRiNmRlYzAwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FlHmYdWWIIGkYQ5gRYDi8wQ37GgA6drx0p-7_onMIB0)这种怎么搞

在脚本刚运行时连接成功了，但脚本执行到了这里时，失去联系了
![image](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/91291b19-46f1-48b3-9395-611be36b45d0)

你的安卓设备是不是和你的电脑失去联系了(比如安卓虚拟机关机，阻止了ADB调试)，或者没有允许ADB调试，ADB没有开启图像识别、模拟点击的权限

**Comment by Pain2021** [comment]
![1707819037837](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/70928776/1f55849e-b28f-48e3-a33c-bc9149791aa9)
airtest看了一下，端口是5554.然后修改了一下端口。现在报错如图。

**Comment by Pain2021** [comment]
![1707819764564](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/70928776/9e058e79-d5af-4834-9dac-b15dcf45ba0c)
airtest远程连接端口是5555.

**Comment by cndaqiang** [comment]
> ![1707819764564](https://private-user-images.githubusercontent.com/70928776/304373646-9e058e79-d5af-4834-9dac-b15dcf45ba0c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4Mjc5NjAsIm5iZiI6MTcwNzgyNzY2MCwicGF0aCI6Ii83MDkyODc3Ni8zMDQzNzM2NDYtOWUwNThlNzktZDVhZi00ODM0LTlkYWMtYjE1ZGNmNDViYTBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEyMzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwM2YxZTNkNDAxZjQyNmIwZTQwNmE0ZDdjMTE4YTc5Zjc4NmVjZTU4MGU4ZTM3ZWFhNWVlM2ZhMTFjMThkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avDPk0iiioaiKtcF1BYjQMNTg-vS-hY6fS8NuT5jQx4) airtest远程连接端口是5555.

嗯，连接地址应该是没有问题的，

我不清楚你运行object.py的终端是否和airtest客户端进行ADB显示画面时，两个ADB冲突了，按照我[上一个回复的做一下](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/5#issuecomment-1940829816)

**Comment by cndaqiang** [comment]
> ![1707819764564](https://private-user-images.githubusercontent.com/70928776/304373646-9e058e79-d5af-4834-9dac-b15dcf45ba0c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjkwNTksIm5iZiI6MTcwNzgyODc1OSwicGF0aCI6Ii83MDkyODc3Ni8zMDQzNzM2NDYtOWUwNThlNzktZDVhZi00ODM0LTlkYWMtYjE1ZGNmNDViYTBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEyNTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYjNmMGEyMjIxYTkzNDk4ZmYyZjAxODRlODE3NDgzMjBlZWQ3NDVlZGIwYmNmMTI5YjFkNDc2N2U1NTY1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ydg3vchSscCbx6kwlbGo7sAOyVC3ETa_wyT9uydjjN4) airtest远程连接端口是5555.

我怀疑是airtest的IDE软件和你在cmd终端中执行object.py冲突了。
因为我刚才测试了，先用cmd终端执行object.py正常控制，这时候我再打开airtestIDE连接虚拟，终端的ADB就会断开，无法进行控制，脚本提示连接失败。

-----

所以要么在airTestIDE软件中执行脚本，要么在终端中执行脚本，不要两个同时打开

**Comment by Pain2021** [comment]
`未运行airtest。修改为以下代码，点击object.py运行，cmd直接迅速闪退`def connect_status(times=10):
    png = Template(r"tpl_target_pos.png", record_pos=(-0.28, 0.153), resolution=(960, 540))
    exists_o(png)
    return True`

**Comment by cndaqiang** [comment]
> 未运行airtest。修改为以下代码，点击object.py运行，cmd直接迅速闪退
> 
> ```
> def connect_status(times=10):
>     png = Template(r"tpl_target_pos.png", record_pos=(-0.28, 0.153), resolution=(960, 540))
>     exists_o(png)
>     return True
> ```

 要么用airtestIDE运行，要么在终端里运行。 
不要点击运行，这样你看不到报错信息。
----
请在cmd/powershell中运行，并提供完整的报错截图记录，
https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/5#issuecomment-1901771876

**Comment by Pain2021** [comment]
cmd里可以运行了。

**Comment by 1181691792** [comment]
连接不上，出现一个架构不同兼容性的问题，psutil 模块尝试加载的库文件（_psutil_osx.abi3.so）是一个不兼容的架构（arm64，需要的是 x86_64），不知道是不是这个导致的

04-28 10:18:40]NNNN:(0)Android:///10.9.196.99:43877:链接失败
[04-28 10:18:40](0)Android:///10.9.196.99:43877:链接失败,重启设备再次连接
[04-28 10:18:40](0)测试远程连接安卓设备by adb reconnect
disconnected 10.9.196.99:43877
connected to 10.9.196.99:43877
[04-28 10:19:41](0)启动成功
[04-28 10:19:41](0)Android:///10.9.196.99:43877:开始第2/4次连接
Traceback (most recent call last):
  File "/Users/huangzhongjun/Downloads/AirTest_MobileAuto_WZRY-master-3/object.py", line 791, in 连接设备
    self.device = connect_device(self.LINK)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/utils/logwraper.py", line 131, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/api.py", line 74, in connect_device
    dev = init_device(platform, uuid, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/api.py", line 41, in init_device
    cls = import_device_cls(platform)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/helper.py", line 246, in import_device_cls
    from airtest.core.android.android import Android as cls
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/android/__init__.py", line 4, in <module>
    from airtest.core.android.android import Android
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/android/android.py", line 14, in <module>
    from airtest.core.android.adb import ADB
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/android/adb.py", line 8, in <module>
    import psutil
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/__init__.py", line 123, in <module>
    from . import _psosx as _psplatform
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psosx.py", line 13, in <module>
    from . import _psposix
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psposix.py", line 28, in <module>
    from . import _psutil_osx
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by 1181691792** [comment]
连接不上，出现一个架构不同兼容性的问题，psutil 模块尝试加载的库文件（_psutil_osx.abi3.so）是一个不兼容的架构（arm64，需要的是 x86_64），不知道是不是这个导致的

04-28 10:18:40]NNNN:(0)Android:///10.9.196.99:43877:链接失败
[04-28 10:18:40](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/0)Android:///10.9.196.99:43877:链接失败,重启设备再次连接
[04-28 10:18:40](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/0)测试远程连接安卓设备by adb reconnect
disconnected 10.9.196.99:43877
connected to 10.9.196.99:43877
[04-28 10:19:41](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/0)启动成功
[04-28 10:19:41](https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/0)Android:///10.9.196.99:43877:开始第2/4次连接
Traceback (most recent call last):
File "/Users/huangzhongjun/Downloads/AirTest_MobileAuto_WZRY-master-3/object.py", line 791, in 连接设备
self.device = connect_device(self.LINK)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/utils/logwraper.py", line 131, in wrapper
res = f(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/api.py", line 74, in connect_device
dev = init_device(platform, uuid, **params)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/api.py", line 41, in init_device
cls = import_device_cls(platform)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/helper.py", line 246, in import_device_cls
from airtest.core.android.android import Android as cls
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/android/init.py", line 4, in 
from airtest.core.android.android import Android
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/android/android.py", line 14, in 
from airtest.core.android.adb import ADB
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/airtest/core/android/adb.py", line 8, in 
import psutil
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/init.py", line 123, in 
from . import _psosx as _psplatform
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psosx.py", line 13, in 
from . import _psposix
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psposix.py", line 28, in 
from . import _psutil_osx
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by 1181691792** [comment]
死活连接不上，出现一个架构不同兼容性的问题，psutil 模块尝试加载的库文件（_psutil_osx.abi3.so）是一个不兼容的架构（arm64，需要的是 x86_64），不知道是不是这个导致的连接失败

**Comment by 1181691792** [comment]
> 出现

解决冲突后，就成功连接了

**Comment by alen157** [comment]
希望来个刷战令任务的

**Comment by alen157** [comment]
一直在这个页面寻找大半天都不带动的什么情况啊
![Uploading mmexport1715151123486.png…]()

**Comment by cndaqiang** [comment]
刷一上午人机，一周的战令就完成了

> 希望来个刷战令任务的

**Comment by cndaqiang** [comment]
> 死活连接不上，出现一个架构不同兼容性的问题，psutil 模块尝试加载的库文件（_psutil_osx.abi3.so）是一个不兼容的架构（arm64，需要的是 x86_64），不知道是不是这个导致的连接失败

我的x86 intel （windows/MacOS） arm64（ubuntu）都可以

**Comment by wwww11h** [comment]
容器优化是要怎么改 为啥在这里会报错
