### ISSUE TITLE
修改代码中客户端的ip地址auto_airtest>LINK_dict[i]=根本找不到在哪里

### ISSUE THREAD

**Issue by 1181691792** [cndaqiang/AirTest_MobileAuto_WZRY#7]
修改代码中客户端的ip地址auto_airtest>LINK_dict[i]=根本找不到在哪里

**Comment by cndaqiang** [comment]
修改这里
<img width="494" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/db011c21-8a46-449a-8b33-6b6da46581ed">
函数解释
<img width="615" alt="image" src="https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/assets/26620270/35d4faf7-2d1f-4753-a6f8-98de8e941000">

README里面给了具体修改的示例：
https://github.com/cndaqiang/AirTest_MobileAuto_WZRY/issues/5
